version: '2'
services:
  Prueba:
    image: angular:10
    working_dir: /app
    ports:
      - 4201:4201
    volumes:
      - ./:/app:delegated
    command: ["ng", "serve", "--port", "4201", "--host", "0.0.0.0"]
